# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mypocket < Formula
  desc ""
  homepage ""
  version "0.4.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/atuy1213/mypocket/releases/download/v0.4.3/mypocket_Darwin_x86_64.tar.gz"
      sha256 "4826b150a6d46f321e1d002bbd94e08a34dc87a9d20e17e137bd256cd249d555"

      def install
        bin.install "mypocket"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/atuy1213/mypocket/releases/download/v0.4.3/mypocket_Darwin_arm64.tar.gz"
      sha256 "d74b2a52b69143335c7cebc30c08de11fd2f3d9e8e358e3fece47421651604fd"

      def install
        bin.install "mypocket"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/atuy1213/mypocket/releases/download/v0.4.3/mypocket_Linux_arm64.tar.gz"
      sha256 "0121100ef55d02b1430bb2280214503f61b03a302930933bbdbe02003f543678"

      def install
        bin.install "mypocket"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/atuy1213/mypocket/releases/download/v0.4.3/mypocket_Linux_x86_64.tar.gz"
      sha256 "0cdb50bc9903b319ab2413e261028b3c1bcdf04f198f7275e0b6f9970832a529"

      def install
        bin.install "mypocket"
      end
    end
  end
end
