# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mypocket < Formula
  desc ""
  homepage ""
  version "0.2.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/atuy1213/mypocket/releases/download/v0.2.8/mypocket_Darwin_x86_64.tar.gz"
      sha256 "5bc1d442e3f460175edde8314b4c4b52a63bc83cd7206b97f3df2fe2048c65ee"

      def install
        bin.install "mypocket"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/atuy1213/mypocket/releases/download/v0.2.8/mypocket_Darwin_arm64.tar.gz"
      sha256 "699a475b25b7b2313f0082be19bf16b253686a68ed6c129981001d96293fc224"

      def install
        bin.install "mypocket"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/atuy1213/mypocket/releases/download/v0.2.8/mypocket_Linux_arm64.tar.gz"
      sha256 "42dd19aab325c2e6047ac6048d2caac310aeb0c39961a70e36d19b3e8e4b1d5d"

      def install
        bin.install "mypocket"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/atuy1213/mypocket/releases/download/v0.2.8/mypocket_Linux_x86_64.tar.gz"
      sha256 "a7b1cee4699c6f26467638a3f35917a89b10317daae4688bdb56e3bbe50a002c"

      def install
        bin.install "mypocket"
      end
    end
  end
end
